### ISSUE TITLE
Trajs of results

### ISSUE THREAD

**Issue by GCVulnerability** [ozyyshr/RepoGraph#2]
Hi, thanks for your wonderful work in enhancing the SWE-bench tasks.
Could you please provide the files generated by the intermediate steps of Agentless (such as loc_output.jsonl)?

**Comment by ozyyshr** [comment]
Hi, thanks for your interest in our work! The logs/files generated by the intermediate steps of Agentless is separately stored for each instance as "localization" and "repair" of the [trajs](https://github.com/swe-bench/experiments/tree/main/evaluation/lite/20240808_RepoGraph_gpt4o/trajs).

**Comment by GCVulnerability** [comment]
Thanks for reply. I will check them!☺️
