### ISSUE TITLE
Corrupted cache archive

### ISSUE THREAD

**Issue by GCVulnerability** [ozyyshr/RepoGraph#3]
Hello, when I tried to reproduce the work of Agentless+RepoGraph, I found that I could not get the compressed package you uploaded on Google Drive because it was marked as a damaged file. 
At the same time, I found that you did not provide requirements.txt, which made it impossible for me to rebuild the warehouse structure graph myself.

**Comment by ozyyshr** [comment]
Hi, thanks for your comment! I have just fixed the Google Drive link with the correct file and updated the requirements.txt for reproducibility.

**Comment by GCVulnerability** [comment]
Many thanks for your fixing and have a good week!
