### ISSUE TITLE
Missing `tqdm` in requirements.txt

### ISSUE THREAD

**Issue by ariel-frischer** [ozyyshr/RepoGraph#5]
Hey, noticed I had some dependency issues when trying to run this for the first time, I had a few other errors but missing `tqdm` was the simplest issue.

**Comment by MrZilinXiao** [comment]
Hello! Thanks for your interest in the project. I have fixed most of the dependency issues and provided a minimum bash script for reproducing the results on two types of integration environments. Please let us know if you experience any issues.
