### ISSUE TITLE
Repograph cache link does not work

### ISSUE THREAD

**Issue by Hodge931** [ozyyshr/RepoGraph#8]
The repograph cache link does not work: https://drive.google.com/file/d/1VXflI_85p3iboI8e22N34zogu6nwT2z7/view?usp=sharing, It says that it has been moved to the trash. Thanks!

**Comment by MrZilinXiao** [comment]
Check the new cache here: https://drive.google.com/file/d/1-0d-OgGoOf3i54bWcf8H0egjQyTSZ8dG/view

Sorry for the inconvenience brought.

**Comment by Hodge931** [comment]
Thanks a lot for the update!

I would like to know if it is possible to get repograph for the full swe-bench data? When I run `python ./repograph/construct_graph.py <dir_to_repo>`, the running seems to break up from time to time. Is this expected?
